### PR TITLE
Rough in listing of pinned Jobs in Slack.

### PR DESCRIPTION
**Pull request by brianherbert**
Related to Issue #22 

This pull requests shouldn't be considered complete. It lacks style, sort/ordering, and any additional information that the reader may need to understand the context from which this information came.

## Todo

- [ ] Proper use of Handlebars (one partial per listing)
- [ ] Sort the JSON in order of newest to oldest
- [ ] Deal with obfuscated usernames in a pleasant way
- [ ] Style the list to match the rest of the site

### CODE REVIEW

**Comment by shpolina** [comment]
Great job! Is the plan to merge this PR and complete other items as part of separate PRs or to continue develop this PR until complete?

**Comment by brianherbert** [comment]
@shpolina Totally missed your comment, sorry for taking so long to respond. It's up to you all if it looks good enough to roll now. It shows the listings but it's not in a compelling format:

screen shot 2018-06-04 at 1 37 57 pm

**Comment by ericlathrop** [comment]
If you put a `jobs.json` file in the `/data` folder I think you should be able to loop over the jobs with this handlebars code in your `src/jobs/index.html.hbs` file:
```
      {{#each jobs}}
        {{message.text}}
      {{/each}}
```

**Comment by brianherbert** [comment]
So I'm pulling the json from another server (https://louisvilletech.aced.cc/messages.json), can I use handlebars? I'm assuming everything is precompiled so I'm not sure how to deal with that situation.

**Comment by ericlathrop** [comment]
When we deploy this, we'll just run the `jobs.json` generating script on the louisvilletech.org server as a cron job before the job that generates the site.

**Comment by brianherbert** [comment]
So when pinning/unpinning messages in Slack, it should update the site in (near) real time. I'm thinking the solution is to just compile the handlebars templates for the jobs json at run time, unless I'm missing something.

**Comment by ericlathrop** [comment]
I'm okay with it not updating instantly. The cron job to generate the site runs every 15 minutes, and I think that's frequent enough for job listings.

**Comment by brianherbert** [comment]
Ah, got it. I assumed it ran once on deploy. Sounds good to me.

**Comment by ericlathrop** [comment]
This has been implemented. [See here.](https://louisvilletech.org/jobs.html) Thanks for your work on this @brianherbert!

**Pull request closed without merging**
