### PR TITLE
Jay smith add January event

### PR DESCRIPTION
**Pull request by JaySmith502**
Adding free LFPL event to discuss Social Media, Privacy and Online Safety in January.

### CODE REVIEW

**Comment by ericlathrop** [comment]
@JaySmith502 When I tested this, the calendar returns a 404. Can you update the URL with a working one?

**Comment by JaySmith502** [comment]
Updated Calendar link with updated Google Calendar share link

**Comment by ericlathrop** [comment]
@JaySmith502 Sorry, I need the `.ics` link. It's under "Calendar Settings"->"Integrate Calendar"->"Public address in iCal format" in Google Calendar.

**Comment by JaySmith502** [comment]
Ahh, I’ll have to get it when I get back from downtown

**Comment by JaySmith502** [comment]
Just updated the link (hopefully correctly)

**Comment by ericlathrop** [comment]
Merged, and deployed!

**Comment by JaySmith502** [comment]
Thanks!

**Pull request merged**
